version: '2'
services:
  sam-postgres-db:
    image: postgres:10.5-alpine
    container_name: checkin-service-postgres-db
    environment:
    - POSTGRES_DB=checkin_requests
    - POSTGRES_PASSWORD=localpasswordsimplepassword
    ports:
    - '5432:5432'
    networks:
      checkinservice:
    volumes:
    - ./init-test-db.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  checkinservice:
